week3 Tasks
muhammedgamal12/JobHacker-System pull request #4
Opened 2023-04-20 23:45 UTC by muhammedgamal12

2023-05-25 11:27 UTC, mohamedshaker9 requested changes

2023-05-25 11:27 UTC, mohamedshaker9 commented on Tasks/src/Min_Max.java
> +        }
For better programming extract this code to new function called for example fillingArrayWithRandomNumbers

2023-05-25 11:27 UTC, mohamedshaker9 commented on Tasks/src/Fibonacci.java
Print the values

2023-05-25 11:27 UTC, mohamedshaker9 commented on Tasks/src/Remove_Duplicates.java
> +public class Remove_Duplicates {
The class name should be start with capital letter for each word. ex: RemoveDuplicates

2023-05-25 11:27 UTC, mohamedshaker9 commented on Tasks/src/Common_Array.java
> +    public  static int[] common_members(int []arr1 , int []arr2 )
method names should be written as camel case and start with a verb. ex, combineCommonValues

2023-05-25 11:27 UTC, mohamedshaker9 commented on Tasks/src/Adding_TwoArrays.java
sort the resulting array

2023-05-25 11:27 UTC, mohamedshaker9 commented on Tasks/src/Difference_Elements.java
if this for task 12 you may not understood the task.
You Have only one array and you have to print the differnce between the minimum and maximum elements in the array.
for example:
intput: {1, 5, 7, 2, 10, 14, 12}
the result : 13

2023-06-05 16:51 UTC, muhammedgamal12 commented on Tasks/src/Fibonacci.java
already printed , please can you explain more..

2023-06-06 19:07 UTC, mohamedshaker9 approved these changes

2023-06-17 15:26 UTC, merged